when:
  - event: push
    branch: master

steps:
  - name: gen 
    image: ruby:3.2 
    commands: |
      sha=$(git rev-parse --short HEAD)
      git config --global user.name "Rajdeep Malakar"
      git config --global user.email "rajdeepm.dev@gmail.com"
      
      gem install ronn-ng >/dev/null

      ronn --roff man/hay_utils.md --manual=hay/utils.h --organization="Hay Foundation"
      git add man/hay_utils.3
      git commit -s -m "[$sha] manpage [CI SKIP]" || true
      git remote remove origin

  - name: push
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: master
      local_ref: master
      ssh_key:
        from_secret: ssh_key
      remote: git@codeberg.org:hay/utils.git
